def menu_and_help(user_role, logged_in_user):
    if logged_in_user == None :
        print("=========== HELP ===========")
        print("Kamu belum login sebagai role apapun. Silahkan login terlebih dahulu.")
        print("1. Login: Masuk ke dalam akun yang sudah terdaftar")
        print("2. Register: Membuat akun baru")
        print("Footnote :")
        print("1. Untuk menggunakan aplikasi, silahkan masukkan nama fungsi yang terdaftar")
        print("2. Jangan lupa untuk memasukkan input yang valid")
    else:
        print("=========== HELP ===========")
        if user_role.lower() == "admin":
            print("Selamat datang, Admin",logged_in_user)
            print("Berikut adalah hal-hal yang dapat kamu lakukan:")
            print("1. Logout: Keluar dari akun yang sedang digunakan")
            print("2. Shop Management: Melakukan manajemen pada SHOP sebagai tempat jual beli peralatan Agent")
            print("3. Monster Management : Menambahkan monster pada database")
            print("4. Save : Menyimpan data game")
            print("5. Exit : Keluar  dari game")
            print("Footnote:")
            print("1. Untuk menggunakan aplikasi, masukkan nama fungsi yang terdaftar")
            print("2. Pastikan memasukkan input yang valid")
        else: 
            print("Halo Agent",logged_in_user+" .Kamu memanggil command HELP. Kamu memilih jalan yang benar, semoga") 
            print("kamu tidak sesat kemudian. Berikut adalah hal-hal yang dapat kamu lakukan sekarang:")
            print("1. Logout : Keluar dari akun yang sedang digunakan")
            print("2. Inventory : Melihat monsters dan items yang dimiliki Agent")
            print("3. Owcadex : Membuka OWCADEX untuk melihat list monsters")
            print("4. Battle : Melakukan battle dengan monster lain")
            print("5. Arena : Menginisiasi Arena untuk melatih monster")
            print("6. Shop : Membuka shop untuk membeli items")
            print("7. Laboratory : Menaikan level monster yang dimiliki")
            print("8. Jackpot : Melakukan gacha")
            print("9. Save : Menyimpan data game")
            print("10. Exit : Keluar dari game")
            print("Footnote:")
            print("1. Untuk menggunakan aplikasi, masukkan nama fungsi yang terdaftar")
            print("2. Pastikan memasukkan input yang valid")
